DEFAULT_SETTINGS = {
    'connected': False,
    'api_url': '',
    'api_key': '',
    'pdf_page_width': 595.0,
    'pdf_page_height': 792.0,
    'custom_fields': [],
    'ab_session_h1': '{code} - {title}',
    'ab_session_h2': '{start} / {end}',
    'ab_contribution_h1': '| {code} | / | {start} |',
    'ab_contribution_h2': '| {code} | / | {start} |',
    'isbn': '',
    'issn': '',
    'booktitle_short': '',
    'booktitle_long': '',
    'series': '',
    'series_number': '',
    'pre_print': '',
    'copyright_year': '',
    'site_license_text': 'Creative Commons Attribution 4.0',
    'site_license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'paper_license_icon_url': 'https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png',
    'paper_license_text': 'Content from this work may be used under the terms of the CC BY 4.0 licence (© 2024). Any distribution of this work must maintain attribution to the author(s), title of the work, publisher, and DOI.',
    'location': '',
    'host_info': '',
    'editorial_board': '',
    'editorial_json': '',
    'doi_env': 'test',
    'doi_proto': 'https',
    'doi_domain': 'doi.org',
    'doi_context': '10.18429',
    'doi_organization': 'JACoW',
    'doi_conference': '',
    'doi_user': '',
    'doi_password': '',
    'date': '',
    'toc_grouping': ['contribution'],
    'primary_color': '#F39433',
    'materials': [],
    'duplicate_of_alias': 'duplicate_of',
    'cat_publish_alias': 'CAT_publish'
}
