DEFAULT_SETTINGS = {
    'connected': False,
    'api_url': '',
    'api_key': '',
    'pdf_page_width': 595.0,
    'pdf_page_height': 792.0,
    'custom_fields': [],
    'ab_session_h1': '{code} - {title}',
    'ab_session_h2': '{start} / {end}',
    'ab_contribution_h1': '| {code} | / | {start} |',
    'ab_contribution_h2': '| {code} | / | {start} |',
    'isbn': '123-4-56789-012-3',
    'issn': '1234-5678',
    'booktitle_short': 'CONF2038',
    'booktitle_long': '32nd Full JACoW Conference Name (CONF2038)',
    'series': 'Full JACoW Conference Name',
    'series_number': '32',
    'pre_print': 'pre print statement for Light Peer Review papers',
    'copyright_year': '2038',
    'site_license_text': 'Creative Commons Attribution 4.0',
    'site_license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'paper_license_icon_url': 'https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png',
    'paper_license_text': 'Content from this work may be used under the terms of the CC BY 4.0 licence (© 2024). Any distribution of this work must maintain attribution to the author(s), title of the work, publisher, and DOI.',
    'location': 'City, Prov/State, Country',
    'host_info': 'CONF2038 was hosted by The Laboratory in Laboratory in City, Prov/State, Country from 4 to 10 May, 2038.',
    'editorial_board': 'Editor One (LAB) \nEditor Two (LAB)',
    'editorial_json': '[ { "first_name": "Editor", "last_name": "One", "affiliation": "LAB" }, { "first_name": "Editor", "last_name": "Two", "affiliation": "LAB" } ]',
    'doi_env': 'test',
    'doi_proto': 'https',
    'doi_domain': 'doi.org',
    'doi_context': '10.18429',
    'doi_organization': 'JACoW',
    'doi_conference': 'CONF2038',
    'doi_user': '',
    'doi_password': '',
    'date': 'May, 4-10 2038',
    'toc_grouping': ['contribution'],
    'primary_color': '#F39433',
    'materials': [],
    'duplicate_of_alias': 'duplicate_of',
    'cat_publish_alias': 'CAT_publish'
}
